# EDR.spec — PyInstaller 6.x build konfigürasyonu
# Kullanım: python -m PyInstaller EDR.spec --clean

a = Analysis(
    ['main.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui',
        'PyQt6.QtWidgets',
        'win32evtlog',
        'win32api',
        'wmi',
        'pythoncom',
        'psutil',
        'watchdog',
        'watchdog.observers',
        'watchdog.events',
        'sqlite3',
        'collectors.wmi_monitor',
        'collectors.filesystem_monitor',
        'collectors.task_monitor',
        'collectors.sysmon_monitor',
        'collectors.network_monitor',
        'detection.sigma_engine',
        'detection.engine',
        'response.responder',
        'core.event_bus',
        'core.cleanup_manager',
        'core.cache_manager',
        'core.scoring',
        'core.suppression_engine',
        'core.timeline_engine',
        'core.logger',
        'storage.database',
        'gui.bridge',
        'gui.main_window',
        'gui.alert_table',
        'gui.process_feed',
        'gui.stats_widget',
        'gui.tray_icon',
        'gui.styles',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='EDR-Koruma-Sistemi',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
